/**
 * AI Nutrition Schemas - SINGLE SOURCE OF TRUTH
 *
 * Schemas specifici per la generazione AI nel dominio nutrizione.
 * Include definizioni per gli output dei meal composer e nutrition agents.
 *
 * @module @onecoach/schemas/nutrition/ai
 */

import { z } from 'zod';
import { MacrosSchema } from './base.schemas';

/**
 * Macros schema with stricter limits for AI generation context
 */
export const AIMacrosSchema = MacrosSchema.extend({
  calories: z.number().min(0).max(2000),
  protein: z.number().min(0).max(100),
  carbs: z.number().min(0).max(100),
  fats: z.number().min(0).max(100),
  fiber: z.number().min(0).max(50).optional(),
});

/**
 * AI Food Item Schema
 * Represents a food item generated or processed by AI.
 * Includes optional metadata fields like barcode/brand that might be inferred.
 */
export const AIFoodItemSchema = z.object({
  id: z.string().optional(), // May be generated by AI or by us
  name: z.string().min(1).max(255),
  quantity: z.number().positive(),
  unit: z.string().default('g'),
  macros: AIMacrosSchema,
  notes: z.string().optional(),
  
  // Optional metadata fields
  foodItemId: z.string().optional(), // If AI provides existing ID (from catalogs)
  brandName: z.string().optional(),
  barcode: z.string().optional(),
  servingSize: z.number().optional(),
  imageUrl: z.string().url().optional(),
  
  // Tracking fields (for completed meals context)
  done: z.boolean().optional(),
  actualQuantity: z.number().optional(),
  actualMacros: AIMacrosSchema.optional(),
});

export type AIFoodItem = z.infer<typeof AIFoodItemSchema>;
